// Sauvegarde complète Hornafresh — schéma (reconstruit via le catalogue Postgres) + données +
// comptes + images. Sans mot de passe base : utilise l'API REST (service role) et l'API de
// gestion Supabase (SUPABASE_ACCESS_TOKEN dans .env.local, droit Database).
//
//   node scripts/backup.mjs [label]        → C:\Users\bongo\hornafresh-backups\<date>-<label>\
//
import fs from 'node:fs';
import path from 'node:path';
import { createClient } from '@supabase/supabase-js';

const REF = 'sneuexxysxlwpokhkjho';
const URL_ = `https://${REF}.supabase.co`;
const KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZXVleHh5c3hsd3Bva2hramhvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODc1Mzc5OSwiZXhwIjoyMDk0MzI5Nzk5fQ.w9Cq_gPz4OIIjFKOx2mlyLnqERSCe-3p6SYILmb1HJs';
const H = { apikey: KEY, Authorization: 'Bearer ' + KEY };

const env = Object.fromEntries(fs.readFileSync('.env.local', 'utf8').split(/\r?\n/)
  .filter(l => l.includes('=') && !l.trim().startsWith('#'))
  .map(l => { const i = l.indexOf('='); return [l.slice(0, i).trim(), l.slice(i + 1).trim().replace(/^["']|["']$/g, '')]; }));
if (!env.SUPABASE_ACCESS_TOKEN) throw new Error('SUPABASE_ACCESS_TOKEN manquant dans .env.local');

const label = (process.argv[2] || 'backup').replace(/[^a-z0-9-]+/gi, '-').toLowerCase();
const stamp = new Date().toISOString().slice(0, 10);
const OUT = path.join('C:/Users/bongo/hornafresh-backups', `${stamp}-${label}`);
fs.mkdirSync(path.join(OUT, 'data'), { recursive: true });
fs.mkdirSync(path.join(OUT, 'storage', 'product-images'), { recursive: true });
const manifest = { date: new Date().toISOString(), label, tables: {}, auth_users: 0, storage_files: 0, schema: {}, errors: [] };

// ── SQL via l'API de gestion ──────────────────────────────────────────────
async function sql(query) {
  const r = await fetch(`https://api.supabase.com/v1/projects/${REF}/database/query`, {
    method: 'POST', headers: { Authorization: 'Bearer ' + env.SUPABASE_ACCESS_TOKEN, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query }),
  });
  if (!r.ok) throw new Error(`SQL HTTP ${r.status}: ${(await r.text()).slice(0, 200)}`);
  return r.json();
}
const qi = s => '"' + s.replace(/"/g, '""') + '"';

// ── 1) Schéma ────────────────────────────────────────────────────────────
const out = [];
out.push(`-- Hornafresh — schéma reconstruit depuis le catalogue le ${manifest.date}`);
out.push(`-- Rejouable dans Supabase SQL Editor (ou via l'API de gestion). Ordre : tables → contraintes → index → fonctions → vues → triggers → RLS → policies.\n`);

const ext = await sql(`select extname, extversion from pg_extension order by 1`);
out.push('-- Extensions présentes : ' + ext.map(e => `${e.extname} ${e.extversion}`).join(', ') + '\n');

const cols = await sql(`
  select c.relname as table_name, a.attname as column_name, a.attnum,
         format_type(a.atttypid, a.atttypmod) as type, a.attnotnull,
         pg_get_expr(d.adbin, d.adrelid) as default_expr, a.attidentity
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid join pg_namespace n on n.oid = c.relnamespace
  left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
  where n.nspname = 'public' and c.relkind = 'r' and a.attnum > 0 and not a.attisdropped
  order by c.relname, a.attnum`);
const byTable = {};
for (const c of cols) (byTable[c.table_name] ||= []).push(c);
out.push('-- ── TABLES ──');
for (const [t, cs] of Object.entries(byTable)) {
  const lines = cs.map(c => {
    let s = `  ${qi(c.column_name)} ${c.type}`;
    if (c.attidentity === 'a') s += ' generated always as identity';
    else if (c.attidentity === 'd') s += ' generated by default as identity';
    else if (c.default_expr) s += ` default ${c.default_expr}`;
    if (c.attnotnull) s += ' not null';
    return s;
  });
  out.push(`create table if not exists public.${qi(t)} (\n${lines.join(',\n')}\n);\n`);
}
manifest.schema.tables = Object.keys(byTable).length;

const cons = await sql(`
  select c.conrelid::regclass::text as table_name, c.conname, c.contype, pg_get_constraintdef(c.oid) as def
  from pg_constraint c join pg_namespace n on n.oid = c.connamespace
  where n.nspname = 'public' order by (c.contype = 'f'), c.conrelid::regclass::text, c.conname`);
out.push('-- ── CONTRAINTES (clés primaires, uniques, checks, puis clés étrangères) ──');
for (const c of cons) out.push(`alter table ${c.table_name} drop constraint if exists ${qi(c.conname)}; alter table ${c.table_name} add constraint ${qi(c.conname)} ${c.def};`);
out.push('');
manifest.schema.constraints = cons.length;

const conNames = new Set(cons.map(c => c.conname));
const idx = await sql(`select tablename, indexname, indexdef from pg_indexes where schemaname = 'public' order by 1, 2`);
out.push('-- ── INDEX (hors index de contraintes) ──');
for (const i of idx) if (!conNames.has(i.indexname)) out.push(i.indexdef.replace(/^create (unique )?index /i, (m, u) => `create ${u || ''}index if not exists `) + ';');
out.push('');
manifest.schema.indexes = idx.filter(i => !conNames.has(i.indexname)).length;

const fns = await sql(`
  select p.proname, pg_get_functiondef(p.oid) as def
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind = 'f' order by 1`);
out.push('-- ── FONCTIONS ──');
for (const f of fns) out.push(f.def.trim() + ';\n');
manifest.schema.functions = fns.length;

const views = await sql(`select table_name, pg_get_viewdef(('public.' || quote_ident(table_name))::regclass, true) as def
  from information_schema.views where table_schema = 'public' order by 1`);
out.push('-- ── VUES ──');
for (const v of views) out.push(`create or replace view public.${qi(v.table_name)} as\n${v.def.trim()}\n`);
manifest.schema.views = views.length;

const trg = await sql(`
  select t.tgname, t.tgrelid::regclass::text as table_name, pg_get_triggerdef(t.oid) as def
  from pg_trigger t join pg_class c on c.oid = t.tgrelid join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and not t.tgisinternal order by 2, 1`);
out.push('-- ── TRIGGERS ──');
for (const t of trg) out.push(`drop trigger if exists ${qi(t.tgname)} on ${t.table_name}; ${t.def};`);
out.push('');
manifest.schema.triggers = trg.length;

const rls = await sql(`select tablename, rowsecurity from pg_tables where schemaname = 'public' order by 1`);
out.push('-- ── RLS ──');
for (const r of rls) out.push(`alter table public.${qi(r.tablename)} ${r.rowsecurity ? 'enable' : 'disable'} row level security;`);
out.push('');

const pol = await sql(`select schemaname, tablename, policyname, permissive, roles::text, cmd, qual, with_check
  from pg_policies where schemaname in ('public', 'storage') order by 1, 2, 3`);
out.push('-- ── POLICIES (public + storage) ──');
for (const p of pol) {
  const roles = p.roles.replace(/^\{|\}$/g, '').split(',').map(r => r.trim()).filter(Boolean).join(', ') || 'public';
  let s = `drop policy if exists ${qi(p.policyname)} on ${p.schemaname}.${qi(p.tablename)};\ncreate policy ${qi(p.policyname)} on ${p.schemaname}.${qi(p.tablename)} as ${p.permissive.toLowerCase()} for ${p.cmd.toLowerCase()} to ${roles}`;
  if (p.qual) s += `\n  using (${p.qual})`;
  if (p.with_check) s += `\n  with check (${p.with_check})`;
  out.push(s + ';\n');
}
manifest.schema.policies = pol.length;
fs.writeFileSync(path.join(OUT, 'schema.sql'), out.join('\n'));
console.log(`schema.sql : ${manifest.schema.tables} tables, ${cons.length} contraintes, ${manifest.schema.indexes} index, ${fns.length} fonctions, ${views.length} vues, ${trg.length} triggers, ${pol.length} policies`);

// ── 2) Données (REST, paginé) ─────────────────────────────────────────────
const spec = await (await fetch(URL_ + '/rest/v1/', { headers: H })).json();
fs.writeFileSync(path.join(OUT, 'schema-openapi.json'), JSON.stringify(spec, null, 2));
const viewNames = new Set(views.map(v => v.table_name));
for (const t of Object.keys(spec.definitions || {})) {
  if (viewNames.has(t)) continue; // vues : pas de données propres
  const rows = [];
  try {
    for (let from = 0; ; from += 1000) {
      const r = await fetch(`${URL_}/rest/v1/${t}?select=*`, { headers: { ...H, Range: `${from}-${from + 999}` } });
      if (!r.ok) throw new Error(`${t}: HTTP ${r.status}`);
      const page = await r.json(); rows.push(...page);
      if (page.length < 1000) break;
    }
    fs.writeFileSync(path.join(OUT, 'data', `${t}.json`), JSON.stringify(rows, null, 2));
    manifest.tables[t] = rows.length;
  } catch (e) { manifest.errors.push(String(e.message)); }
}
console.log(`données : ${Object.keys(manifest.tables).length} tables, ${Object.values(manifest.tables).reduce((a, b) => a + b, 0)} lignes`);

// ── 3) Comptes ────────────────────────────────────────────────────────────
const sb = createClient(URL_, KEY);
const users = [];
for (let page = 1; page <= 50; page++) {
  const { data, error } = await sb.auth.admin.listUsers({ page, perPage: 1000 });
  if (error) { manifest.errors.push('auth: ' + error.message); break; }
  users.push(...(data?.users || [])); if ((data?.users || []).length < 1000) break;
}
fs.writeFileSync(path.join(OUT, 'auth-users.json'), JSON.stringify(users, null, 2));
manifest.auth_users = users.length;

// ── 4) Images ─────────────────────────────────────────────────────────────
async function listAll(prefix = '') {
  const r = await fetch(`${URL_}/storage/v1/object/list/product-images`, { method: 'POST', headers: { ...H, 'Content-Type': 'application/json' }, body: JSON.stringify({ prefix, limit: 1000, offset: 0 }) });
  const items = r.ok ? await r.json() : []; let files = [];
  for (const it of items) { const p = prefix ? `${prefix}/${it.name}` : it.name; if (it.id) files.push(p); else files.push(...await listAll(p)); }
  return files;
}
for (const f of await listAll()) {
  try {
    const r = await fetch(`${URL_}/storage/v1/object/product-images/${encodeURI(f)}`, { headers: H });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    const dest = path.join(OUT, 'storage', 'product-images', f); fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, Buffer.from(await r.arrayBuffer())); manifest.storage_files++;
  } catch (e) { manifest.errors.push(`storage ${f}: ${e.message}`); }
}
console.log(`comptes : ${manifest.auth_users} | images : ${manifest.storage_files}`);

// ── 5) Outils de restauration + manifeste ─────────────────────────────────
fs.copyFileSync(path.join('scripts', 'restore-data.mjs'), path.join(OUT, 'restore-data.mjs'));
if (fs.existsSync('.env.local')) fs.copyFileSync('.env.local', path.join(OUT, 'env.local.backup'));
fs.writeFileSync(path.join(OUT, 'manifest.json'), JSON.stringify(manifest, null, 2));
fs.writeFileSync(path.join(OUT, 'README.md'), `# Sauvegarde Hornafresh — ${stamp} — ${label}

- \`schema.sql\` : schéma complet reconstruit (tables, contraintes, index, fonctions, vues, triggers, RLS, policies). Rejouable dans le SQL Editor.
- \`data/*.json\` : données de chaque table · \`auth-users.json\` : comptes (sans mots de passe) · \`storage/\` : images.
- \`restore-data.mjs\` : restauration des données — depuis le dossier du projet :
  \`node "${OUT.replace(/\\/g, '/')}/restore-data.mjs" --dry\` puis sans \`--dry\` (\`--wipe\` = retour exact, \`--tables a,b\`).
- Rollback du schéma : comparer avec \`schema.sql\` ; supprimer ce qui a été ajouté après (DROP), rejouer ce qui manque.
- \`env.local.backup\` : secrets (ne pas partager).
`);
console.log(`\nDossier : ${OUT}\nErreurs : ${manifest.errors.length ? manifest.errors.join(' | ') : 'aucune'}`);
