-- Planificateur de promos côté admin : textes (fr = valeur par défaut dans le code)
insert into public.ui_translations (key, language_code, value)
select v.key, v.lang, v.value from (values
 ('promo.tab_banners','en','Banners'),('promo.tab_banners','zh','横幅'),('promo.tab_banners','am','ባነሮች'),('promo.tab_banners','so','Calaamado'),('promo.tab_banners','aa','Calaamado'),
 ('promo.tab_products','en','Product promo prices'),('promo.tab_products','zh','产品促销价'),('promo.tab_products','am','የምርት ማስተዋወቂያ ዋጋዎች'),('promo.tab_products','so','Qiimayaasha dhiirrigelinta alaabta'),('promo.tab_products','aa','Qiimayaasha dhiirrigelinta alaabta'),
 ('promo.admin_intro','en','Promo price over a period for Hornafresh products: shown with the old price crossed out, automatic return to the normal price. Merchant promotions are visible here and can be cancelled.'),('promo.admin_intro','zh','Hornafresh 产品在一段时间内的促销价：显示划掉的原价，自动恢复正常价格。商户促销在此可见并可取消。'),('promo.admin_intro','am','ለHornafresh ምርቶች በአንድ ጊዜ ውስጥ የማስተዋወቂያ ዋጋ፦ ከተሰረዘ አሮጌ ዋጋ ጋር ይታያል፣ ወደ መደበኛ ዋጋ በራስ-ሰር ይመለሳል። የነጋዴ ማስተዋወቂያዎች እዚህ ይታያሉ እና ሊሰረዙ ይችላሉ።'),('promo.admin_intro','so','Qiime dhiirrigelin muddo alaabta Hornafresh: la muujiyo qiimihii hore oo la xariiqay, dib-u-noqosho toos ah qiimaha caadiga ah. Dhiirrigelinta ganacsatada halkan ayay ka muuqdaan waana la joojin karaa.'),('promo.admin_intro','aa','Qiime dhiirrigelin muddo alaabta Hornafresh: la muujiyo qiimihii hore oo la xariiqay, dib-u-noqosho toos ah qiimaha caadiga ah. Dhiirrigelinta ganacsatada halkan ayay ka muuqdaan waana la joojin karaa.'),
 ('promo.err_merchant','en','Merchant product: only their shop can put it on promotion.'),('promo.err_merchant','zh','商户产品：只有其店铺可以设置促销。'),('promo.err_merchant','am','የነጋዴ ምርት፦ ሱቁ ብቻ ማስተዋወቂያ ላይ ሊያደርገው ይችላል።'),('promo.err_merchant','so','Alaab ganacsade: kaliya dukaankiisa ayaa dhiirrigelin karo.'),('promo.err_merchant','aa','Alaab ganacsade: kaliya dukaankiisa ayaa dhiirrigelin karo.'),
 ('promo.admin_cancel_note','en','Reason sent to the merchant (optional):'),('promo.admin_cancel_note','zh','发送给商户的原因（可选）：'),('promo.admin_cancel_note','am','ለነጋዴው የተላከ ምክንያት (አማራጭ)፦'),('promo.admin_cancel_note','so','Sababta loo diro ganacsadaha (ikhtiyaari):'),('promo.admin_cancel_note','aa','Sababta loo diro ganacsadaha (ikhtiyaari):'),
 ('promo.show_past','en','Show ended and cancelled'),('promo.show_past','zh','显示已结束和已取消'),('promo.show_past','am','የተጠናቀቁ እና የተሰረዙትን አሳይ'),('promo.show_past','so','Muuji kuwa dhammaaday iyo kuwa la joojiyay'),('promo.show_past','aa','Muuji kuwa dhammaaday iyo kuwa la joojiyay')
) as v(key, lang, value)
where not exists (select 1 from public.ui_translations u where u.key = v.key and u.language_code = v.lang);
select count(*) from public.ui_translations where key in ('promo.tab_banners','promo.tab_products','promo.admin_intro','promo.err_merchant','promo.admin_cancel_note','promo.show_past');
