-- PHASE 12 — Réassort intelligent : traductions de la page « Ma commande modèle » (fr = fallback dans le code)
insert into public.ui_translations (key, language_code, value)
select v.key, v.lang, v.value from (values
 ('sub.paused_low_balance','en','Paused: insufficient balance at the last delivery.'),('sub.paused_low_balance','zh','已暂停：上次配送时余额不足。'),('sub.paused_low_balance','am','ቆሟል፦ በመጨረሻው አቅርቦት ጊዜ ቀሪ ሂሳብ በቂ አልነበረም።'),('sub.paused_low_balance','so','Waa la joojiyay: haraaga kuma filnayn keenistii ugu dambaysay.'),('sub.paused_low_balance','aa','Waa la joojiyay: haraaga kuma filnayn keenistii ugu dambaysay.'),
 ('sub.paused_low_balance_hint','en','It will resume automatically as soon as your wallet covers'),('sub.paused_low_balance_hint','zh','当您的钱包余额足够时将自动恢复：'),('sub.paused_low_balance_hint','am','የቁጠባ ሂሳብዎ ሲሸፍን ወዲያውኑ ይቀጥላል፦'),('sub.paused_low_balance_hint','so','Si toos ah ayay dib u bilaabmi doontaa marka kaydkaagu daboolo'),('sub.paused_low_balance_hint','aa','Si toos ah ayay dib u bilaabmi doontaa marka kaydkaagu daboolo'),
 ('sub.missing','en','missing'),('sub.missing','zh','还差'),('sub.missing','am','ይጎድላል'),('sub.missing','so','waxaa maqan'),('sub.missing','aa','waxaa maqan'),
 ('sub.paused_or_save','en','You can also tick "Activate" and save.'),('sub.paused_or_save','zh','您也可以勾选"启用"并保存。'),('sub.paused_or_save','am','«አግብር» ላይ ምልክት አድርገው ማስቀመጥም ይችላሉ።'),('sub.paused_or_save','so','Waxaad kaloo calaamadayn kartaa «Dhaqaajin» oo kaydin kartaa.'),('sub.paused_or_save','aa','Waxaad kaloo calaamadayn kartaa «Dhaqaajin» oo kaydin kartaa.'),
 ('sub.paused_expired','en','Expired: tick "Activate automatic delivery" and save to restart for one year.'),('sub.paused_expired','zh','已到期：勾选"启用自动配送"并保存，即可重新开始一年。'),('sub.paused_expired','am','ጊዜው አልፏል፦ «ራስ-ሰር አቅርቦት አግብር» ላይ ምልክት አድርገው ለአንድ ዓመት እንደገና ለመጀመር ያስቀምጡ።'),('sub.paused_expired','so','Waa dhacday: calaamadee «Dhaqaaji keenista tooska ah» oo kaydi si aad hal sano dib ugu bilowdo.'),('sub.paused_expired','aa','Waa dhacday: calaamadee «Dhaqaaji keenista tooska ah» oo kaydi si aad hal sano dib ugu bilowdo.'),
 ('sub.next_delivery','en','Next delivery'),('sub.next_delivery','zh','下次配送'),('sub.next_delivery','am','ቀጣይ አቅርቦት'),('sub.next_delivery','so','Keenista xigta'),('sub.next_delivery','aa','Keenista xigta'),
 ('sub.debited_from_wallet','en','debited from your wallet'),('sub.debited_from_wallet','zh','将从您的钱包扣除'),('sub.debited_from_wallet','am','ከቁጠባ ሂሳብዎ ይቀነሳል'),('sub.debited_from_wallet','so','laga jarayo kaydkaaga'),('sub.debited_from_wallet','aa','laga jarayo kaydkaaga'),
 ('sub.missing_before','en','Missing'),('sub.missing_before','zh','还差'),('sub.missing_before','am','ይጎድላል'),('sub.missing_before','so','Waxaa maqan'),('sub.missing_before','aa','Waxaa maqan'),
 ('sub.missing_after','en','in your wallet: top up before that date, otherwise the delivery will be paused.'),('sub.missing_after','zh','在您的钱包中：请在该日期前充值，否则配送将被暂停。'),('sub.missing_after','am','በቁጠባ ሂሳብዎ፦ ከዚያ ቀን በፊት ይሙሉ፣ አለበለዚያ አቅርቦቱ ይቆማል።'),('sub.missing_after','so','kaydkaaga: buuxi taariikhdaas ka hor, haddii kale keenista waa la joojin doonaa.'),('sub.missing_after','aa','kaydkaaga: buuxi taariikhdaas ka hor, haddii kale keenista waa la joojin doonaa.'),
 ('sub.balance_ok','en','Sufficient balance. We will remind you the day before each delivery.'),('sub.balance_ok','zh','余额充足。我们会在每次配送前一天提醒您。'),('sub.balance_ok','am','በቂ ቀሪ ሂሳብ። ከእያንዳንዱ አቅርቦት አንድ ቀን በፊት እናሳውቅዎታለን።'),('sub.balance_ok','so','Haraag ku filan. Waxaan ku xasuusin doonnaa maalinta ka horraysa keenis kasta.'),('sub.balance_ok','aa','Haraag ku filan. Waxaan ku xasuusin doonnaa maalinta ka horraysa keenis kasta.')
) as v(key, lang, value)
where not exists (select 1 from public.ui_translations u where u.key = v.key and u.language_code = v.lang);
