-- PHASE 13 — WhatsApp « cliquer pour discuter » : traductions (fr = fallback dans le code)
insert into public.ui_translations (key, language_code, value)
select v.key, v.lang, v.value from (values
 ('wa.hello','en','Hello Hornafresh, '),('wa.hello','zh','您好 Hornafresh，'),('wa.hello','am','ሰላም Hornafresh፣ '),('wa.hello','so','Salaan Hornafresh, '),('wa.hello','aa','Salaan Hornafresh, '),
 ('wa.i_am','en','I am'),('wa.i_am','zh','我是'),('wa.i_am','am','እኔ'),('wa.i_am','so','waxaan ahay'),('wa.i_am','aa','waxaan ahay'),
 ('wa.contact','en','Write to us on WhatsApp'),('wa.contact','zh','通过 WhatsApp 联系我们'),('wa.contact','am','በ WhatsApp ይጻፉልን'),('wa.contact','so','Nagu soo qor WhatsApp'),('wa.contact','aa','Nagu soo qor WhatsApp'),
 ('wa.contact_short','en','WhatsApp'),('wa.contact_short','zh','WhatsApp'),('wa.contact_short','am','WhatsApp'),('wa.contact_short','so','WhatsApp'),('wa.contact_short','aa','WhatsApp'),
 ('wa.hello_shop','en','Hello'),('wa.hello_shop','zh','您好'),('wa.hello_shop','am','ሰላም'),('wa.hello_shop','so','Salaan'),('wa.hello_shop','aa','Salaan'),
 ('wa.ask_merchant','en','Ask the merchant a question'),('wa.ask_merchant','zh','向商家提问'),('wa.ask_merchant','am','ነጋዴውን ጥያቄ ይጠይቁ'),('wa.ask_merchant','so','Su''aal weydii ganacsadaha'),('wa.ask_merchant','aa','Su''aal weydii ganacsadaha'),
 ('wa.ask_us','en','A question? Write to us on WhatsApp'),('wa.ask_us','zh','有疑问？通过 WhatsApp 联系我们'),('wa.ask_us','am','ጥያቄ አለዎት? በ WhatsApp ይጻፉልን'),('wa.ask_us','so','Su''aal? Nagu soo qor WhatsApp'),('wa.ask_us','aa','Su''aal? Nagu soo qor WhatsApp'),
 ('wa.hello_product','en','Hello, I have a question about'),('wa.hello_product','zh','您好，我想咨询关于'),('wa.hello_product','am','ሰላም፣ ስለ'),('wa.hello_product','so','Salaan, su''aal ayaan ka qabaa'),('wa.hello_product','aa','Salaan, su''aal ayaan ka qabaa'),
 ('checkout.wa_send','en','Send my order on WhatsApp'),('checkout.wa_send','zh','通过 WhatsApp 发送我的订单'),('checkout.wa_send','am','ትዕዛዜን በ WhatsApp ላክ'),('checkout.wa_send','so','Dalabkayga ku dir WhatsApp'),('checkout.wa_send','aa','Dalabkayga ku dir WhatsApp'),
 ('checkout.wa_hint','en','Optional: for a question or a delivery detail, your summary is pre-filled.'),('checkout.wa_hint','zh','可选：如有疑问或配送细节，您的订单摘要已预填。'),('checkout.wa_hint','am','አማራጭ፦ ለጥያቄ ወይም የአቅርቦት ዝርዝር፣ ማጠቃለያዎ ቀድሞ ተሞልቷል።'),('checkout.wa_hint','so','Ikhtiyaari: su''aal ama faahfaahin keenis, kooban-taadu waa la buuxiyay.'),('checkout.wa_hint','aa','Ikhtiyaari: su''aal ama faahfaahin keenis, kooban-taadu waa la buuxiyay.'),
 ('producer.wa_title','en','Shop WhatsApp'),('producer.wa_title','zh','店铺 WhatsApp'),('producer.wa_title','am','የሱቅ WhatsApp'),('producer.wa_title','so','WhatsApp-ka dukaanka'),('producer.wa_title','aa','WhatsApp-ka dukaanka'),
 ('producer.wa_hint','en','Optional. If set, an "Ask the merchant a question" button appears on your shop page and product pages. Orders and payments stay on Hornafresh.'),('producer.wa_hint','zh','可选。填写后，您的店铺页和产品页会显示"向商家提问"按钮。订单和付款仍在 Hornafresh 完成。'),('producer.wa_hint','am','አማራጭ። ከተሞላ «ነጋዴውን ጥያቄ ይጠይቁ» የሚል አዝራር በሱቅዎ እና በምርት ገጾችዎ ላይ ይታያል። ትዕዛዞች እና ክፍያዎች በ Hornafresh ላይ ይቆያሉ።'),('producer.wa_hint','so','Ikhtiyaari. Haddii la buuxiyo, badhanka «Su''aal weydii ganacsadaha» ayaa ka muuqda bogga dukaankaaga iyo boggaga alaabtaada. Dalabyada iyo lacag-bixinta waxay ku sii jiraan Hornafresh.'),('producer.wa_hint','aa','Ikhtiyaari. Haddii la buuxiyo, badhanka «Su''aal weydii ganacsadaha» ayaa ka muuqda bogga dukaankaaga iyo boggaga alaabtaada. Dalabyada iyo lacag-bixinta waxay ku sii jiraan Hornafresh.'),
 ('producer.wa_ph','en','e.g. 77 12 34 56'),('producer.wa_ph','zh','例如：77 12 34 56'),('producer.wa_ph','am','ምሳሌ፦ 77 12 34 56'),('producer.wa_ph','so','Tusaale: 77 12 34 56'),('producer.wa_ph','aa','Tusaale: 77 12 34 56'),
 ('producer.wa_save','en','Save'),('producer.wa_save','zh','保存'),('producer.wa_save','am','አስቀምጥ'),('producer.wa_save','so','Kaydi'),('producer.wa_save','aa','Kaydi'),
 ('producer.wa_ok','en','Number saved: the WhatsApp button is visible on your shop page.'),('producer.wa_ok','zh','号码已保存：WhatsApp 按钮已显示在您的店铺页。'),('producer.wa_ok','am','ቁጥሩ ተቀምጧል፦ የ WhatsApp አዝራር በሱቅዎ ላይ ይታያል።'),('producer.wa_ok','so','Lambarka waa la kaydiyay: badhanka WhatsApp wuxuu ka muuqdaa bogga dukaankaaga.'),('producer.wa_ok','aa','Lambarka waa la kaydiyay: badhanka WhatsApp wuxuu ka muuqdaa bogga dukaankaaga.'),
 ('producer.wa_removed','en','Number removed: no more WhatsApp button on your shop page.'),('producer.wa_removed','zh','号码已移除：您的店铺页不再显示 WhatsApp 按钮。'),('producer.wa_removed','am','ቁጥሩ ተወግዷል፦ በሱቅዎ ላይ የ WhatsApp አዝራር የለም።'),('producer.wa_removed','so','Lambarka waa la saaray: badhanka WhatsApp kama muuqdo bogga dukaankaaga.'),('producer.wa_removed','aa','Lambarka waa la saaray: badhanka WhatsApp kama muuqdo bogga dukaankaaga.'),
 ('producer.wa_invalid','en','Invalid number: 8 digits (Djibouti) or international format.'),('producer.wa_invalid','zh','号码无效：8位数字（吉布提）或国际格式。'),('producer.wa_invalid','am','ልክ ያልሆነ ቁጥር፦ 8 አሃዞች (ጅቡቲ) ወይም ዓለም አቀፍ ቅርጸት።'),('producer.wa_invalid','so','Lambar aan sax ahayn: 8 lambar (Jabuuti) ama qaab caalami ah.'),('producer.wa_invalid','aa','Lambar aan sax ahayn: 8 lambar (Jabuuti) ama qaab caalami ah.')
) as v(key, lang, value)
where not exists (select 1 from public.ui_translations u where u.key = v.key and u.language_code = v.lang);
