-- =====================================================================
-- PHASE 1 ③-B — Page « Mon abonnement » (espace marchand) : textes d'interface
-- Aucun changement de schéma (tables merchant_plans / merchant_subscriptions inchangées).
-- fr = valeur par défaut dans le code.
-- =====================================================================

-- Bandeau : le message « contactez le 77 43 26 15 » est remplacé par un lien vers la page
update public.ui_translations set value = v.value
from (values
  ('en','No active subscription — your products are not visible on the site. Activate your subscription to make them visible.'),
  ('zh','没有有效订阅——您的产品在网站上不可见。请激活订阅以使其可见。'),
  ('am','ንቁ ምዝገባ የለም — ምርቶችዎ በድረ-ገጹ ላይ አይታዩም። እንዲታዩ ምዝገባዎን ያንቁ።'),
  ('so','Rukun firfircoon ma jiro — badeecooyinkaagu kama muuqdaan bogga. Hawlgeli rukunkaaga si ay u muuqdaan.'),
  ('aa','Rukun firfircoon ma jiro — badeecooyinkaagu kama muuqdaan bogga. Hawlgeli rukunkaaga si ay u muuqdaan.')
) as v(lang, value)
where ui_translations.key = 'producer.sub_none' and ui_translations.language_code = v.lang;

insert into public.ui_translations (key, language_code, value)
select v.key, v.lang, v.value from (values
  ('producer.nav_subscription','en','My subscription'),('producer.nav_subscription','zh','我的订阅'),('producer.nav_subscription','am','የእኔ ምዝገባ'),('producer.nav_subscription','so','Rukunkayga'),('producer.nav_subscription','aa','Rukunkayga'),
  ('producer.sub_link_view','en','View my request'),('producer.sub_link_view','zh','查看我的申请'),('producer.sub_link_view','am','ጥያቄዬን ይመልከቱ'),('producer.sub_link_view','so','Eeg codsigayga'),('producer.sub_link_view','aa','Eeg codsigayga'),
  ('producer.sub_link_renew','en','Renew'),('producer.sub_link_renew','zh','续订'),('producer.sub_link_renew','am','አድስ'),('producer.sub_link_renew','so','Cusboonaysii'),('producer.sub_link_renew','aa','Cusboonaysii'),
  ('producer.sub_link_activate','en','Activate my subscription'),('producer.sub_link_activate','zh','激活我的订阅'),('producer.sub_link_activate','am','ምዝገባዬን አንቃ'),('producer.sub_link_activate','so','Hawlgeli rukunkayga'),('producer.sub_link_activate','aa','Hawlgeli rukunkayga'),
  ('producer.sub_days_left','en','day(s) left'),('producer.sub_days_left','zh','天剩余'),('producer.sub_days_left','am','ቀን(ኖች) ቀርተዋል'),('producer.sub_days_left','so','maalmood ayaa haray'),('producer.sub_days_left','aa','maalmood ayaa haray'),
  ('producer.sub_method_cash','en','Cash'),('producer.sub_method_cash','zh','现金'),('producer.sub_method_cash','am','ጥሬ ገንዘብ'),('producer.sub_method_cash','so','Lacag cadaan'),('producer.sub_method_cash','aa','Lacag cadaan'),
  ('producer.sub_ref','en','Ref.'),('producer.sub_ref','zh','参考号'),('producer.sub_ref','am','ማጣቀሻ'),('producer.sub_ref','so','Tix.'),('producer.sub_ref','aa','Tix.'),
  ('producer.sub_suspended_title','en','Subscription suspended'),('producer.sub_suspended_title','zh','订阅已暂停'),('producer.sub_suspended_title','am','ምዝገባ ታግዷል'),('producer.sub_suspended_title','so','Rukunka waa la joojiyay'),('producer.sub_suspended_title','aa','Rukunka waa la joojiyay'),
  ('producer.sub_suspended_hint','en','Contact Hornafresh on 77 43 26 15 to reactivate it.'),('producer.sub_suspended_hint','zh','请联系 Hornafresh：77 43 26 15 以重新激活。'),('producer.sub_suspended_hint','am','እንደገና ለማንቃት Hornafresh ን በ77 43 26 15 ያግኙ።'),('producer.sub_suspended_hint','so','La xiriir Hornafresh 77 43 26 15 si dib loogu hawlgeliyo.'),('producer.sub_suspended_hint','aa','La xiriir Hornafresh 77 43 26 15 si dib loogu hawlgeliyo.'),
  ('producer.sub_expired_title','en','Subscription expired'),('producer.sub_expired_title','zh','订阅已过期'),('producer.sub_expired_title','am','ምዝገባ አብቅቷል'),('producer.sub_expired_title','so','Rukunka waa dhacay'),('producer.sub_expired_title','aa','Rukunka waa dhacay'),
  ('producer.sub_expired_hint','en','Your products are no longer visible. Renew below.'),('producer.sub_expired_hint','zh','您的产品已不再显示。请在下方续订。'),('producer.sub_expired_hint','am','ምርቶችዎ ከእንግዲህ አይታዩም። ከታች ያድሱ።'),('producer.sub_expired_hint','so','Badeecooyinkaagu mar dambe ma muuqdaan. Hoos ka cusboonaysii.'),('producer.sub_expired_hint','aa','Badeecooyinkaagu mar dambe ma muuqdaan. Hoos ka cusboonaysii.'),
  ('producer.sub_none_title','en','No active subscription'),('producer.sub_none_title','zh','没有有效订阅'),('producer.sub_none_title','am','ንቁ ምዝገባ የለም'),('producer.sub_none_title','so','Rukun firfircoon ma jiro'),('producer.sub_none_title','aa','Rukun firfircoon ma jiro'),
  ('producer.sub_none_hint','en','Activate your subscription below to make your products visible on Hornafresh.'),('producer.sub_none_hint','zh','请在下方激活订阅，让您的产品在 Hornafresh 上可见。'),('producer.sub_none_hint','am','ምርቶችዎ በHornafresh ላይ እንዲታዩ ከታች ምዝገባዎን ያንቁ።'),('producer.sub_none_hint','so','Hoos ka hawlgeli rukunkaaga si badeecooyinkaagu ugu muuqdaan Hornafresh.'),('producer.sub_none_hint','aa','Hoos ka hawlgeli rukunkaaga si badeecooyinkaagu ugu muuqdaan Hornafresh.'),
  ('producer.sub_cancel_request','en','Withdraw my declaration'),('producer.sub_cancel_request','zh','撤回我的申报'),('producer.sub_cancel_request','am','መግለጫዬን አንሳ'),('producer.sub_cancel_request','so','Ka noqo sheegashadayda'),('producer.sub_cancel_request','aa','Ka noqo sheegashadayda'),
  ('producer.sub_cancel_confirm','en','Withdraw this payment declaration?'),('producer.sub_cancel_confirm','zh','撤回此付款申报？'),('producer.sub_cancel_confirm','am','ይህን የክፍያ መግለጫ ማንሳት ይፈልጋሉ?'),('producer.sub_cancel_confirm','so','Ka noqo sheegashadan lacag bixinta?'),('producer.sub_cancel_confirm','aa','Ka noqo sheegashadan lacag bixinta?'),
  ('producer.sub_renew_title','en','Renew my subscription'),('producer.sub_renew_title','zh','续订我的订阅'),('producer.sub_renew_title','am','ምዝገባዬን አድስ'),('producer.sub_renew_title','so','Cusboonaysii rukunkayga'),('producer.sub_renew_title','aa','Cusboonaysii rukunkayga'),
  ('producer.sub_activate_title','en','Activate my subscription'),('producer.sub_activate_title','zh','激活我的订阅'),('producer.sub_activate_title','am','ምዝገባዬን አንቃ'),('producer.sub_activate_title','so','Hawlgeli rukunkayga'),('producer.sub_activate_title','aa','Hawlgeli rukunkayga'),
  ('producer.sub_renew_desc','en','The new period will start the day after your current subscription ends, i.e. on'),('producer.sub_renew_desc','zh','新周期将在当前订阅结束后的次日开始，即'),('producer.sub_renew_desc','am','አዲሱ ጊዜ የአሁኑ ምዝገባዎ ካበቃ በኋላ በሚቀጥለው ቀን ይጀምራል፣ ማለትም'),('producer.sub_renew_desc','so','Muddada cusub waxay bilaaban doontaa maalinta ka dambaysa dhamaadka rukunkaaga hadda, taas oo ah'),('producer.sub_renew_desc','aa','Muddada cusub waxay bilaaban doontaa maalinta ka dambaysa dhamaadka rukunkaaga hadda, taas oo ah'),
  ('producer.sub_activate_desc','en','Pay the amount, then declare your payment: Hornafresh checks it and activates your subscription.'),('producer.sub_activate_desc','zh','支付金额后申报付款：Hornafresh 核实后将激活您的订阅。'),('producer.sub_activate_desc','am','መጠኑን ይክፈሉ፣ ከዚያ ክፍያዎን ያሳውቁ፦ Hornafresh ያረጋግጣል እና ምዝገባዎን ያነቃል።'),('producer.sub_activate_desc','so','Bixi lacagta, ka dibna sheeg lacag bixintaada: Hornafresh ayaa hubin doona oo hawlgelin doona rukunkaaga.'),('producer.sub_activate_desc','aa','Bixi lacagta, ka dibna sheeg lacag bixintaada: Hornafresh ayaa hubin doona oo hawlgelin doona rukunkaaga.'),
  ('producer.sub_days','en','days'),('producer.sub_days','zh','天'),('producer.sub_days','am','ቀናት'),('producer.sub_days','so','maalmood'),('producer.sub_days','aa','maalmood'),
  ('producer.sub_waafi_instructions','en','Send the amount to the Hornafresh Waafi number below, then enter the transaction reference.'),('producer.sub_waafi_instructions','zh','将金额发送至下方 Hornafresh Waafi 号码，然后输入交易参考号。'),('producer.sub_waafi_instructions','am','መጠኑን ከታች ወዳለው የHornafresh Waafi ቁጥር ይላኩ፣ ከዚያ የግብይቱን ማጣቀሻ ያስገቡ።'),('producer.sub_waafi_instructions','so','U dir lacagta lambarka Waafi ee Hornafresh ee hoose, ka dibna geli tixraaca wareejinta.'),('producer.sub_waafi_instructions','aa','U dir lacagta lambarka Waafi ee Hornafresh ee hoose, ka dibna geli tixraaca wareejinta.'),
  ('producer.sub_ref_ph','en','e.g. Waafi transaction reference'),('producer.sub_ref_ph','zh','例如：Waafi 交易参考号'),('producer.sub_ref_ph','am','ምሳሌ፦ የWaafi ግብይት ማጣቀሻ'),('producer.sub_ref_ph','so','Tusaale: tixraaca wareejinta Waafi'),('producer.sub_ref_ph','aa','Tusaale: tixraaca wareejinta Waafi'),
  ('producer.sub_cash_instructions','en','Hand the amount in cash to the Hornafresh team (77 43 26 15). You can add a note below (date, person).'),('producer.sub_cash_instructions','zh','将现金交给 Hornafresh 团队（77 43 26 15）。您可以在下方添加备注（日期、经手人）。'),('producer.sub_cash_instructions','am','መጠኑን በጥሬ ገንዘብ ለHornafresh ቡድን (77 43 26 15) ያስረክቡ። ከታች ማስታወሻ ማከል ይችላሉ (ቀን፣ ሰው)።'),('producer.sub_cash_instructions','so','U gudbi lacagta cadaan kooxda Hornafresh (77 43 26 15). Hoos ku dari kartaa qoraal (taariikh, qof).'),('producer.sub_cash_instructions','aa','U gudbi lacagta cadaan kooxda Hornafresh (77 43 26 15). Hoos ku dari kartaa qoraal (taariikh, qof).'),
  ('producer.sub_note_ph','en','e.g. handed on 24/09 to Salah'),('producer.sub_note_ph','zh','例如：9 月 24 日交给 Salah'),('producer.sub_note_ph','am','ምሳሌ፦ በ24/09 ለሳላህ ተሰጠ'),('producer.sub_note_ph','so','Tusaale: la gudbiyay 24/09 Salah'),('producer.sub_note_ph','aa','Tusaale: la gudbiyay 24/09 Salah'),
  ('producer.sub_declared','en','Declaration sent. Hornafresh will confirm your payment shortly.'),('producer.sub_declared','zh','申报已发送。Hornafresh 将很快确认您的付款。'),('producer.sub_declared','am','መግለጫ ተልኳል። Hornafresh በቅርቡ ክፍያዎን ያረጋግጣል።'),('producer.sub_declared','so','Sheegashada waa la diray. Hornafresh dhowaan ayay xaqiijin doontaa lacag bixintaada.'),('producer.sub_declared','aa','Sheegashada waa la diray. Hornafresh dhowaan ayay xaqiijin doontaa lacag bixintaada.'),
  ('producer.sub_declare_btn','en','I have paid — send my declaration'),('producer.sub_declare_btn','zh','我已付款——发送申报'),('producer.sub_declare_btn','am','ከፍያለሁ — መግለጫዬን ላክ'),('producer.sub_declare_btn','so','Waan bixiyay — dir sheegashadayda'),('producer.sub_declare_btn','aa','Waan bixiyay — dir sheegashadayda'),
  ('producer.sub_declare_note','en','Your subscription is activated once Hornafresh verifies the payment. You will be notified.'),('producer.sub_declare_note','zh','Hornafresh 核实付款后将激活您的订阅。您将收到通知。'),('producer.sub_declare_note','am','Hornafresh ክፍያውን ካረጋገጠ በኋላ ምዝገባዎ ይነቃል። ማሳወቂያ ይደርስዎታል።'),('producer.sub_declare_note','so','Rukunkaaga waa la hawlgelin doonaa marka Hornafresh xaqiijiso lacag bixinta. Waa lagu ogeysiin doonaa.'),('producer.sub_declare_note','aa','Rukunkaaga waa la hawlgelin doonaa marka Hornafresh xaqiijiso lacag bixinta. Waa lagu ogeysiin doonaa.'),
  ('producer.sub_declare_confirm','en','Do you confirm you have made this payment? Hornafresh will verify it and then activate your subscription.'),('producer.sub_declare_confirm','zh','您确认已完成此付款吗？Hornafresh 核实后将激活您的订阅。'),('producer.sub_declare_confirm','am','ይህን ክፍያ መፈጸምዎን ያረጋግጣሉ? Hornafresh ያረጋግጥና ምዝገባዎን ያነቃል።'),('producer.sub_declare_confirm','so','Ma xaqiijinaysaa inaad samaysay lacag bixintan? Hornafresh ayaa hubin doona ka dibna hawlgelin doona rukunkaaga.'),('producer.sub_declare_confirm','aa','Ma xaqiijinaysaa inaad samaysay lacag bixintan? Hornafresh ayaa hubin doona ka dibna hawlgelin doona rukunkaaga.'),
  ('producer.sub_ref_required','en','Enter your Waafi transaction reference.'),('producer.sub_ref_required','zh','请输入您的 Waafi 交易参考号。'),('producer.sub_ref_required','am','የWaafi ግብይት ማጣቀሻዎን ያስገቡ።'),('producer.sub_ref_required','so','Geli tixraaca wareejintaada Waafi.'),('producer.sub_ref_required','aa','Geli tixraaca wareejintaada Waafi.'),
  ('producer.sub_pending_exists','en','A declaration is already awaiting confirmation.'),('producer.sub_pending_exists','zh','已有一份申报正在等待确认。'),('producer.sub_pending_exists','am','አንድ መግለጫ አስቀድሞ ማረጋገጫ በመጠባበቅ ላይ ነው።'),('producer.sub_pending_exists','so','Sheegasho ayaa horay u sugaysa xaqiijin.'),('producer.sub_pending_exists','aa','Sheegasho ayaa horay u sugaysa xaqiijin.'),
  ('producer.sub_history','en','History'),('producer.sub_history','zh','历史记录'),('producer.sub_history','am','ታሪክ'),('producer.sub_history','so','Taariikh'),('producer.sub_history','aa','Taariikh'),
  ('producer.sub_history_empty','en','No subscription yet.'),('producer.sub_history_empty','zh','暂无订阅。'),('producer.sub_history_empty','am','እስካሁን ምንም ምዝገባ የለም።'),('producer.sub_history_empty','so','Rukun ma jiro weli.'),('producer.sub_history_empty','aa','Rukun ma jiro weli.'),
  ('producer.sub_col_date','en','Date'),('producer.sub_col_date','zh','日期'),('producer.sub_col_date','am','ቀን'),('producer.sub_col_date','so','Taariikh'),('producer.sub_col_date','aa','Taariikh'),
  ('producer.sub_col_plan','en','Plan'),('producer.sub_col_plan','zh','套餐'),('producer.sub_col_plan','am','እቅድ'),('producer.sub_col_plan','so','Qorshe'),('producer.sub_col_plan','aa','Qorshe'),
  ('producer.sub_col_period','en','Period'),('producer.sub_col_period','zh','周期'),('producer.sub_col_period','am','ጊዜ'),('producer.sub_col_period','so','Muddo'),('producer.sub_col_period','aa','Muddo'),
  ('producer.sub_col_amount','en','Amount'),('producer.sub_col_amount','zh','金额'),('producer.sub_col_amount','am','መጠን'),('producer.sub_col_amount','so','Qadar'),('producer.sub_col_amount','aa','Qadar'),
  ('producer.sub_col_method','en','Method'),('producer.sub_col_method','zh','方式'),('producer.sub_col_method','am','ዘዴ'),('producer.sub_col_method','so','Hab'),('producer.sub_col_method','aa','Hab'),
  ('producer.sub_col_status','en','Status'),('producer.sub_col_status','zh','状态'),('producer.sub_col_status','am','ሁኔታ'),('producer.sub_col_status','so','Xaalad'),('producer.sub_col_status','aa','Xaalad'),
  ('producer.sub_status_cancelled','en','Withdrawn'),('producer.sub_status_cancelled','zh','已撤回'),('producer.sub_status_cancelled','am','ተነስቷል'),('producer.sub_status_cancelled','so','La noqday'),('producer.sub_status_cancelled','aa','La noqday'),
  ('producer.sub_status_rejected','en','Rejected'),('producer.sub_status_rejected','zh','已拒绝'),('producer.sub_status_rejected','am','ውድቅ ተደርጓል'),('producer.sub_status_rejected','so','La diiday'),('producer.sub_status_rejected','aa','La diiday')
) as v(key, lang, value)
where not exists (select 1 from public.ui_translations u where u.key = v.key and u.language_code = v.lang);

-- ROLLBACK : delete from public.ui_translations where key like 'producer.sub\_%' and key not in
--   ('producer.sub_expiring','producer.sub_renew_hint','producer.sub_active','producer.sub_pending','producer.sub_suspended','producer.sub_none');
