-- PHASE 6 — promotions planifiées : textes (fr = valeur par défaut dans le code)
insert into public.ui_translations (key, language_code, value)
select v.key, v.lang, v.value from (values
 ('producer.nav_promotions','en','My promotions'),('producer.nav_promotions','zh','我的促销'),('producer.nav_promotions','am','የእኔ ማስተዋወቂያዎች'),('producer.nav_promotions','so','Dhiirrigelintayda'),('producer.nav_promotions','aa','Dhiirrigelintayda'),
 ('product.promo_until','en','Promo until'),('product.promo_until','zh','促销截止'),('product.promo_until','am','ማስተዋወቂያ እስከ'),('product.promo_until','so','Dhiirrigelin ilaa'),('product.promo_until','aa','Dhiirrigelin ilaa'),
 ('promo.intro','en','Schedule a promo price over a period: the site shows the promo price with the old price crossed out, then returns to the normal price automatically. No re-validation.'),('promo.intro','zh','在一段时间内安排促销价：网站显示促销价并划掉原价，之后自动恢复正常价格。无需重新审核。'),('promo.intro','am','በአንድ ጊዜ ውስጥ የማስተዋወቂያ ዋጋ ያቅዱ፦ ድረ-ገጹ የማስተዋወቂያውን ዋጋ ከአሮጌው ዋጋ ጋር ተሰርዞ ያሳያል፣ ከዚያ በራስ-ሰር ወደ መደበኛው ዋጋ ይመለሳል። ዳግም ማረጋገጫ የለም።'),('promo.intro','so','Qorshee qiime dhiirrigelin muddo: bogga wuxuu muujinayaa qiimaha dhiirrigelinta iyo qiimihii hore oo la xariiqay, ka dibna si toos ah ayuu ugu noqdaa qiimaha caadiga ah. Dib-u-ansixin ma jirto.'),('promo.intro','aa','Qorshee qiime dhiirrigelin muddo: bogga wuxuu muujinayaa qiimaha dhiirrigelinta iyo qiimihii hore oo la xariiqay, ka dibna si toos ah ayuu ugu noqdaa qiimaha caadiga ah. Dib-u-ansixin ma jirto.'),
 ('promo.new','en','New promotion'),('promo.new','zh','新促销'),('promo.new','am','አዲስ ማስተዋወቂያ'),('promo.new','so','Dhiirrigelin cusub'),('promo.new','aa','Dhiirrigelin cusub'),
 ('promo.no_products','en','No published product: publish a product first.'),('promo.no_products','zh','没有已发布的产品：请先发布产品。'),('promo.no_products','am','የታተመ ምርት የለም፦ መጀመሪያ ምርት ያትሙ።'),('promo.no_products','so','Alaab la daabacay ma jirto: marka hore daabac alaab.'),('promo.no_products','aa','Alaab la daabacay ma jirto: marka hore daabac alaab.'),
 ('promo.product','en','Product'),('promo.product','zh','产品'),('promo.product','am','ምርት'),('promo.product','so','Alaab'),('promo.product','aa','Alaab'),
 ('promo.price','en','Promo price (Fdj)'),('promo.price','zh','促销价（Fdj）'),('promo.price','am','የማስተዋወቂያ ዋጋ (Fdj)'),('promo.price','so','Qiimaha dhiirrigelinta (Fdj)'),('promo.price','aa','Qiimaha dhiirrigelinta (Fdj)'),
 ('promo.price_ph','en','e.g.'),('promo.price_ph','zh','例如：'),('promo.price_ph','am','ምሳሌ፦'),('promo.price_ph','so','Tusaale:'),('promo.price_ph','aa','Tusaale:'),
 ('promo.vs','en','compared to'),('promo.vs','zh','相比'),('promo.vs','am','ከ ጋር ሲነጻጸር'),('promo.vs','so','marka loo eego'),('promo.vs','aa','marka loo eego'),
 ('promo.from','en','From'),('promo.from','zh','从'),('promo.from','am','ከ'),('promo.from','so','Laga bilaabo'),('promo.from','aa','Laga bilaabo'),
 ('promo.to','en','To'),('promo.to','zh','至'),('promo.to','am','እስከ'),('promo.to','so','Ilaa'),('promo.to','aa','Ilaa'),
 ('promo.schedule','en','Schedule'),('promo.schedule','zh','安排'),('promo.schedule','am','ያቅዱ'),('promo.schedule','so','Qorshee'),('promo.schedule','aa','Qorshee'),
 ('promo.created','en','Promotion scheduled.'),('promo.created','zh','促销已安排。'),('promo.created','am','ማስተዋወቂያ ታቅዷል።'),('promo.created','so','Dhiirrigelin la qorsheeyay.'),('promo.created','aa','Dhiirrigelin la qorsheeyay.'),
 ('promo.list','en','Promotions'),('promo.list','zh','促销'),('promo.list','am','ማስተዋወቂያዎች'),('promo.list','so','Dhiirrigelinno'),('promo.list','aa','Dhiirrigelinno'),
 ('promo.empty','en','No promotion yet.'),('promo.empty','zh','暂无促销。'),('promo.empty','am','እስካሁን ምንም ማስተዋወቂያ የለም።'),('promo.empty','so','Weli dhiirrigelin ma jirto.'),('promo.empty','aa','Weli dhiirrigelin ma jirto.'),
 ('promo.cancel','en','Cancel'),('promo.cancel','zh','取消'),('promo.cancel','am','ሰርዝ'),('promo.cancel','so','Jooji'),('promo.cancel','aa','Jooji'),
 ('promo.cancel_confirm','en','Cancel this promotion? The normal price applies immediately.'),('promo.cancel_confirm','zh','取消此促销？正常价格将立即生效。'),('promo.cancel_confirm','am','ይህን ማስተዋወቂያ ይሰርዙ? መደበኛው ዋጋ ወዲያውኑ ይተገበራል።'),('promo.cancel_confirm','so','Jooji dhiirrigelintan? Qiimaha caadiga ah ayaa isla markiiba dhaqan gala.'),('promo.cancel_confirm','aa','Jooji dhiirrigelintan? Qiimaha caadiga ah ayaa isla markiiba dhaqan gala.'),
 ('promo.state_active','en','🔥 Running'),('promo.state_active','zh','🔥 进行中'),('promo.state_active','am','🔥 በሂደት ላይ'),('promo.state_active','so','🔥 Socota'),('promo.state_active','aa','🔥 Socota'),
 ('promo.state_upcoming','en','🗓️ Upcoming'),('promo.state_upcoming','zh','🗓️ 即将开始'),('promo.state_upcoming','am','🗓️ የሚመጣ'),('promo.state_upcoming','so','🗓️ Soo socota'),('promo.state_upcoming','aa','🗓️ Soo socota'),
 ('promo.state_ended','en','Ended'),('promo.state_ended','zh','已结束'),('promo.state_ended','am','ተጠናቋል'),('promo.state_ended','so','Dhammaatay'),('promo.state_ended','aa','Dhammaatay'),
 ('promo.state_cancelled','en','Cancelled'),('promo.state_cancelled','zh','已取消'),('promo.state_cancelled','am','ተሰርዟል'),('promo.state_cancelled','so','La joojiyay'),('promo.state_cancelled','aa','La joojiyay'),
 ('promo.err_invalid','en','Incomplete fields.'),('promo.err_invalid','zh','字段不完整。'),('promo.err_invalid','am','ያልተሟሉ መስኮች።'),('promo.err_invalid','so','Meelo aan buuxin.'),('promo.err_invalid','aa','Meelo aan buuxin.'),
 ('promo.err_not_published','en','The product must be published.'),('promo.err_not_published','zh','产品必须已发布。'),('promo.err_not_published','am','ምርቱ መታተም አለበት።'),('promo.err_not_published','so','Alaabta waa in la daabacaa.'),('promo.err_not_published','aa','Alaabta waa in la daabacaa.'),
 ('promo.err_price','en','The promo price must be lower than the normal price.'),('promo.err_price','zh','促销价必须低于正常价格。'),('promo.err_price','am','የማስተዋወቂያ ዋጋ ከመደበኛው ዋጋ ያነሰ መሆን አለበት።'),('promo.err_price','so','Qiimaha dhiirrigelintu waa inuu ka hooseeyaa qiimaha caadiga ah.'),('promo.err_price','aa','Qiimaha dhiirrigelintu waa inuu ka hooseeyaa qiimaha caadiga ah.'),
 ('promo.err_past','en','The start date cannot be in the past.'),('promo.err_past','zh','开始日期不能是过去。'),('promo.err_past','am','የመጀመሪያ ቀን ያለፈ ሊሆን አይችልም።'),('promo.err_past','so','Taariikhda bilowga ma noqon karto mid la soo dhaafay.'),('promo.err_past','aa','Taariikhda bilowga ma noqon karto mid la soo dhaafay.'),
 ('promo.err_end','en','The end date must be after the start.'),('promo.err_end','zh','结束日期必须在开始之后。'),('promo.err_end','am','የመጨረሻ ቀን ከመጀመሪያው በኋላ መሆን አለበት።'),('promo.err_end','so','Taariikhda dhammaadku waa inay ka dambaysaa bilowga.'),('promo.err_end','aa','Taariikhda dhammaadku waa inay ka dambaysaa bilowga.'),
 ('promo.err_long','en','90 days maximum.'),('promo.err_long','zh','最多 90 天。'),('promo.err_long','am','ከፍተኛ 90 ቀናት።'),('promo.err_long','so','90 maalmood ugu badnaan.'),('promo.err_long','aa','90 maalmood ugu badnaan.'),
 ('promo.err_overlap','en','A promotion is already scheduled on this product for these dates.'),('promo.err_overlap','zh','该产品在这些日期已有促销安排。'),('promo.err_overlap','am','በዚህ ምርት ላይ ለእነዚህ ቀናት ማስተዋወቂያ አስቀድሞ ታቅዷል።'),('promo.err_overlap','so','Dhiirrigelin ayaa horay loogu qorsheeyay alaabtan taariikhahan.'),('promo.err_overlap','aa','Dhiirrigelin ayaa horay loogu qorsheeyay alaabtan taariikhahan.')
) as v(key, lang, value)
where not exists (select 1 from public.ui_translations u where u.key = v.key and u.language_code = v.lang);
select count(*) from public.ui_translations where key like 'promo.%' or key in ('producer.nav_promotions','product.promo_until');
