-- PHASE 8 — récapitulatif quotidien : textes (fr = valeur par défaut dans le code)
insert into public.ui_translations (key, language_code, value)
select v.key, v.lang, v.value from (values
 ('producer.email_pref_title','en','Order e-mails'),('producer.email_pref_title','zh','订单邮件'),('producer.email_pref_title','am','የትዕዛዝ ኢሜይሎች'),('producer.email_pref_title','so','Emaylada dalabka'),('producer.email_pref_title','aa','Emaylada dalabka'),
 ('producer.email_pref_hint','en','In-app and phone notifications stay immediate. Only choose how often you get e-mails.'),('producer.email_pref_hint','zh','应用内和手机通知保持即时。仅选择邮件的频率。'),('producer.email_pref_hint','am','በመተግበሪያ እና በስልክ ማሳወቂያዎች ወዲያውኑ ይቀጥላሉ። የኢሜይል ድግግሞሽን ብቻ ይምረጡ።'),('producer.email_pref_hint','so','Ogeysiisyada app-ka iyo taleefanka waxay ahaanayaan degdeg. Kaliya dooro inta jeer ee aad emaylka helayso.'),('producer.email_pref_hint','aa','Ogeysiisyada app-ka iyo taleefanka waxay ahaanayaan degdeg. Kaliya dooro inta jeer ee aad emaylka helayso.'),
 ('producer.email_instant','en','One e-mail per order'),('producer.email_instant','zh','每个订单一封邮件'),('producer.email_instant','am','ለእያንዳንዱ ትዕዛዝ አንድ ኢሜይል'),('producer.email_instant','so','Hal emayl dalab kasta'),('producer.email_instant','aa','Hal emayl dalab kasta'),
 ('producer.email_instant_desc','en','You know right away what to supply.'),('producer.email_instant_desc','zh','您立即知道需要供应什么。'),('producer.email_instant_desc','am','ምን እንደሚያቀርቡ ወዲያውኑ ያውቃሉ።'),('producer.email_instant_desc','so','Isla markiiba waad ogaataa waxaad keenayso.'),('producer.email_instant_desc','aa','Isla markiiba waad ogaataa waxaad keenayso.'),
 ('producer.email_daily','en','One daily summary'),('producer.email_daily','zh','每日一份摘要'),('producer.email_daily','am','በቀን አንድ ማጠቃለያ'),('producer.email_daily','so','Hal koobitaan maalin kasta'),('producer.email_daily','aa','Hal koobitaan maalin kasta'),
 ('producer.email_daily_desc','en','Every morning: orders received, low stock, amount to be paid out, subscription.'),('producer.email_daily_desc','zh','每天早上：收到的订单、库存不足、应转付金额、订阅。'),('producer.email_daily_desc','am','በየማለዳው፦ የተቀበሉ ትዕዛዞች፣ ዝቅተኛ ክምችት፣ የሚከፈል መጠን፣ ምዝገባ።'),('producer.email_daily_desc','so','Subax kasta: dalabyada la helay, kayd yar, qadarka la gudbinayo, rukun.'),('producer.email_daily_desc','aa','Subax kasta: dalabyada la helay, kayd yar, qadarka la gudbinayo, rukun.')
) as v(key, lang, value)
where not exists (select 1 from public.ui_translations u where u.key = v.key and u.language_code = v.lang);
select count(*) from public.ui_translations where key like 'producer.email_%';
